$ANSIBLE_VAULT;1.1;AES256
61363164326636666335356361333432343333356261356461393564363663656636643233626364
3237343365313565643236313866353563316262383361380a626135363939323535353463626466
34353336666135313033386564383665326164373861343162663937653562323930623965656164
3164323034316535390a333336393563613431316433393166313033383130623337653738373538
32356135363062383139396530306339643662356239333634313738356561306562
