$ANSIBLE_VAULT;1.1;AES256
38333364643464623031363938353738386336383536306262393138613864326564386138316132
3533313163383230393033616632366565663537323838350a323237373764633533643666663534
66306330616533313163323664333630623239613164386439356461393238316637663732383535
6230653135656164300a623037366361356635376338643465616536646661353435386332306534
30376333316466343335666237623965373566356231353330653233626162376564
