$ANSIBLE_VAULT;1.1;AES256
36336262666330666438313834623037356439356436306533353065393533376162633863313933
6435343065666561653265633131646265323439336131330a363063386239633530346365373435
30313133373334653235633138343336386161356430393364336634323634343062393432323733
3462633531393765660a623631396237646463663737363839353732313766383630363663613730
6161
