---
- name: Demonstrate ansible tags 
  hosts: localhost
  become: true
  tasks:
  - name: Task1
    ansible.builtin.debug:
      msg: "Task 1 - Red planet"
    tags: mars
  - name: Task2
    ansible.builtin.debug:
      msg: "Task 2 - Venus planet"
    tags: mint
  - name: Task3
    ansible.builtin.debug:
      msg: "Task 3 - Jupiter planet"
    tags: mosaic
  - name: Task4
    ansible.builtin.debug:
      msg: "Task 4 - Earth planet"
    tags: 
    - blue 
    - green
...
#Run this play book with below options
# ansible-playbook --tags=mars play117.yml
# ansible-playbook --tags "mint" play117.yml
# ansible-playbook -t=mosaic play117.yml
# ansible-playbook --tags="blue,mist" play117.yml
# ansible-playbook --tags "green,mist" play117.yml
# ansible-playbook --skip-tags="green,mist" play117.yml
# ansible-playbook --skip-tags "green,mist" play117.yml
# ansible-playbook --list-tags play117.yml
# ansible-playbook --step play117.yml
# ansible-playbook --tags all play117.yml
