---
- name: Demonstrate variables by hosts
#Get variables defined in the file
  hosts: 
   - 192.168.1.31
   - 192.168.1.32
   - 192.168.1.40
  gather_facts: no
  tasks:
  - name: print variable value
    ansible.builtin.debug:
      msg: "OS is : {{ os }}, color: {{ color}}"
...