---
- name: Create a user with given variable
  hosts: localhost
  become: yes
  remote_user: ansible
  become_user: root
  gather_facts: no
  vars_files:
   - vars/sec.yml
  tasks:
  - name: create user
    ansible.builtin.user:
      name: jk
      password: "{{ passwd|password_hash('sha512') }}"
      update_password: on_create
      state: present
...