---
- name: copy multiple files with a loop
  hosts: web
  become: yes
  vars:
    f_list:
    - orig: /etc/httpd/conf/httpd.conf
      destn: /var/tmp/httpd.conf
    - orig: /var/www/html/index.html
      destn: /var/tmp/index.html
  tasks:
  - name: copy files
    copy:
      src: "{{ item.orig }}"
      dest: "{{ item.destn }}"
    loop: "{{ f_list }}"
...