---
#configure cron job
#Mins   Hour   Date   Month      Day of Week   Command
#0      8,18,20    1-5   1,3,4,6,   2          /usr/sbin/vgs > /tmp/vgs_output.txt
- name: Demonstrate cron module to schedule a cron job
  hosts: localhost
  become: yes
  tasks:
  - name: Configure cron job
    ansible.builtin.cron:
      name: "My Cron"
      minute: "0" # minutes ranges from 0 to 59
      hour: "8,18,20" #8am,6pm,8pm hours ranges from 0-23
      #ignoring day of the week and week assumed as *
      #weekday: "2" # Tuesday
      day: "1-5" # Day of the month the job should run: in this example date is range from 1 to 5
      month: "1,3,4,6" #Month of the year the job should run: in this example Jan,Mar,Apr,Jun
      job: "/usr/sbin/vgs > /tmp/vgs_output.txt" # this is path to program or script to run
...