---
- name: This is able to creater a directory
  hosts: localhost
  become: true
  tasks:
   - name: creater an empty file
     ansible.builtin.file:
       path: /home/ansible/new_ansi_dir
       #state: directory
       state: absent
       owner: root
       group: ansible
       mode: '0750'
...