---
#configure cron job
#Mins   Hour   Date   Month      Day of Week   Command
#0      8,18,20    1-5   1,3,4,6,   2          /usr/sbin/vgs > /tmp/vgs_output.txt
- name: Demonstrate cron module how to remove schedule a cron job
  hosts: localhost
  become: yes
  tasks:
  - name: remove cron job
    ansible.builtin.cron:
      name: "My Cron"
      state: absent
...