---
- name: Play to copy file from local server to remote server
  hosts: 192.168.1.55
  become: yes
  vars:
    fname: jk.txt
    dest_dir_name: /opt/ansible
  tasks:
  - name: Create dir if it does not exists
    ansible.builtin.file:
      path: "{{ dest_dir_name }}"
      state: directory
      owner: root
      group: root
      mode: '0755'
  - name: Task to copy {{ fname }} from local server two remote server
    ansible.builtin.copy:
      src: "{{ fname }}"
      dest: "{{ dest_dir_name }}"
      backup: yes
...