---
- name: Demonstrate include_vars
  hosts: localhost
  become: true
  tasks:
  - name: task -1 
    ansible.builtin.include_vars: vars/pack.yml
  - name: Task -2
    ansible.builtin.yum:
        name: 
          - "{{ pkg_name1 }}"
          - "{{ pkg_name2 }}"
        state: latest
  - name: Task -3
    ansible.builtin.service:
        name: "{{ ser_name }}"
        state: "{{ ser_state }}"
...