---
- name: Create a user with the variables
  hosts: all
  become: yes
  vars:
    usr:
      user: human
      passwd: human
      comment: "The user is created by god"
      shell: /bin/bash
  tasks:
    - name: Create a user 
      ansible.builtin.user:
        name: "{{ usr.user }}"
        password: "{{ usr.passwd | password_hash('sha512') }}"
        comment: "{{ usr.comment }}"
        shell: "{{ usr.shell }}"
        state: present
...
